In [14]:
import pandas as pd

In [15]:
df = pd.read_excel("../data/raw/Oil well.xlsx", header=2)
df.head()

,Date,\nOil volume (m3/day),Volume of liquid (m3/day),\nGas volume (m3/day),Water volume (m3/day),Water cut (%),\nWorking hours,\nDynamic level (m),\nReservoir pressure (atm)
0,2013-01-01,49,70,13055,21,29,24,1819,214
1,2013-01-02,49,70,13055,21,29,24,1836,214
2,2013-01-03,49,70,13055,21,29,24,1788,214
3,2013-01-04,49,70,13055,21,29,24,1789,214
4,2013-01-05,44,70,11768,26,36,24,1825,214

In [16]:
df.columns

Index(['Date', '\nOil volume (m3/day)', 'Volume of liquid (m3/day)',
       '\nGas volume (m3/day)', 'Water volume (m3/day)', 'Water cut (%) ',
       '\nWorking hours', '\nDynamic level (m)', '\nReservoir pressure (atm)'],
      dtype='object')

In [17]:
df.columns = df.columns.str.replace("\n", " ")
df.columns = df.columns.str.strip()
df.columns

Index(['Date', 'Oil volume (m3/day)', 'Volume of liquid (m3/day)',
       'Gas volume (m3/day)', 'Water volume (m3/day)', 'Water cut (%)',
       'Working hours', 'Dynamic level (m)', 'Reservoir pressure (atm)'],
      dtype='object')

In [18]:
df = df.rename(columns={
    "Date": "date",
    "Oil volume (m3/day)": "oil_volume",
    "Volume of liquid (m3/day)": "liquid_volume",
    "Gas volume (m3/day)": "gas_volume",
    "Water volume (m3/day)": "water_volume",
    "Water cut (%)": "water_cut",
    "Working hours": "working_hours",
    "Dynamic level (m)": "dynamic_level",
    "Reservoir pressure (atm)": "reservoir_pressure"
})

In [19]:
df.columns

Index(['date', 'oil_volume', 'liquid_volume', 'gas_volume', 'water_volume',
       'water_cut', 'working_hours', 'dynamic_level', 'reservoir_pressure'],
      dtype='object')

In [20]:
df.head()

,date,oil_volume,liquid_volume,gas_volume,water_volume,water_cut,working_hours,dynamic_level,reservoir_pressure
0,2013-01-01,49,70,13055,21,29,24,1819,214
1,2013-01-02,49,70,13055,21,29,24,1836,214
2,2013-01-03,49,70,13055,21,29,24,1788,214
3,2013-01-04,49,70,13055,21,29,24,1789,214
4,2013-01-05,44,70,11768,26,36,24,1825,214

In [21]:
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date")
df.head()

,date,oil_volume,liquid_volume,gas_volume,water_volume,water_cut,working_hours,dynamic_level,reservoir_pressure
0,2013-01-01,49,70,13055,21,29,24,1819,214
1,2013-01-02,49,70,13055,21,29,24,1836,214
2,2013-01-03,49,70,13055,21,29,24,1788,214
3,2013-01-04,49,70,13055,21,29,24,1789,214
4,2013-01-05,44,70,11768,26,36,24,1825,214

In [22]:
df.shape

(2939, 9)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2939 entries, 0 to 2938
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                2939 non-null   datetime64[ns]
 1   oil_volume          2939 non-null   int64
 2   liquid_volume       2939 non-null   int64
 3   gas_volume          2939 non-null   int64
 4   water_volume        2939 non-null   int64
 5   water_cut           2939 non-null   int64
 6   working_hours       2939 non-null   int64
 7   dynamic_level       2939 non-null   int64
 8   reservoir_pressure  2939 non-null   int64
dtypes: datetime64[ns](1), int64(8)
memory usage: 206.8 KB

In [24]:
df.describe()

,date,oil_volume,liquid_volume,gas_volume,water_volume,water_cut,working_hours,dynamic_level,reservoir_pressure
count,2939,2939.000000,2939.000000,2939.000000,2939.000000,2939.000000,2939.000000,2939.000000,2939.000000
mean,2017-01-09 16:48:49.976182272,17.624362,59.464103,4730.146308,41.828853,70.694794,22.344675,1930.383464,157.019054
min,2013-01-01 00:00:00,0.000000,12.000000,4.000000,9.000000,29.000000,7.000000,1529.000000,100.000000
25%,2015-01-05 12:00:00,11.000000,50.000000,3041.500000,33.000000,69.000000,22.000000,1855.000000,129.000000
50%,2017-01-10 00:00:00,15.000000,58.000000,3909.000000,43.000000,73.000000,24.000000,1890.000000,157.000000
75%,2019-01-14 12:00:00,22.000000,74.000000,5843.500000,50.000000,76.000000,24.000000,2008.000000,185.500000
max,2021-01-18 00:00:00,49.000000,113.000000,13113.000000,99.000000,100.000000,24.000000,2137.000000,214.000000
std,NaN,9.689026,18.634101,2598.888524,13.056625,9.534203,3.039553,114.543752,32.917150

In [25]:
df.to_csv("../data/processed/oil_well_clean.csv", index=False)

In [26]:
df_clean = pd.read_csv("../data/processed/oil_well_clean.csv")
df_clean.head()

,date,oil_volume,liquid_volume,gas_volume,water_volume,water_cut,working_hours,dynamic_level,reservoir_pressure
0,2013-01-01,49,70,13055,21,29,24,1819,214
1,2013-01-02,49,70,13055,21,29,24,1836,214
2,2013-01-03,49,70,13055,21,29,24,1788,214
3,2013-01-04,49,70,13055,21,29,24,1789,214
4,2013-01-05,44,70,11768,26,36,24,1825,214